---
- name: restart the dogsapp service
  become: yes
  service: 
    name: dogsapp
    state: restarted

- name: restart nginx
  become: yes
  systemd:
    name: nginx
    state: restarted

- name: reload the system daemon
  become: yes
  systemd:
    daemon_reload: yes