---
- name: gather info about EC2 instance
  ec2_instance:
    region: "{{ aws_region }}"
    filters:
      tag:Name: "{{ ec2_instance_name }}"
      instance-state-name: running
  register: ec2_info_data
- debug:
    msg: "{{ ec2_info_data }}"