#!/bin/bash

SYSTEM_DIR=/etc/systemd/system
NGINX_DIR=/etc/nginx

cd setup


ssh midterm <<EOF
	sudo -S yum install git -y;
	sudo yum install nodejs -y;
	sudo yum install npm -y;
	sudo yum install mongodb-server -y;
	sudo systemctl enable mongod;
	sudo systemctl start mongod;

	mkdir /app
	if grep "hichat" /etc/passwd >/dev/null 2>&1;then
		echo "hichat user already existed"
	else
		sudo useradd -m -d /app hichat
		sudo passwd -d hichat
	fi

	sudo yum install nginx -y
	sudo systemctl enable nginx
	sudo systemctl start nginx

	if [ ! -f $NGINX_DIR/nginx.service ]; then
        	sudo mv ~/nginx.conf $NGINX_DIR
	else
		sudo rm $NGINX_DIR/nginx.conf
		sudo mv ~/nginx.conf $NGINX_DIR
	fi

        if [ ! -f $SYSTEM_DIR/todoapp.service ]; then
                sudo mv ~/todoapp.service $SYSTEM_DIR
        else
                sudo rm $SYSTEM_DIR/todoapp.service
                sudo mv ~/todoapp.service $SYSTEM_DIR
        fi

	sudo chmod 755 /app
	sudo -S su - hichat;
	echo "Start Cloning"
	cd /app
       	sudo git clone https://github.com/wayou/HiChat.git
	cd HiChat
	sudo npm install
        

	sudo systemctl restart nginx
	sudo systemctl daemon-reload
	sudo systemctl enable todoapp
	sudo systemctl start todoapp	
EOF

